### ISSUE TITLE
[Infrared-detect-by-segmentation]在线测试demo相关的问题

### ISSUE THREAD

**Issue by liforeversong** [Linaom1214/Infrared-detect-by-segmentation#1]
Linaom1214老师，您好，我想用您的[Infrared-detect-by-segmentation]在线测试demo，测试几张红外小目标图像，但是一直提示
error。还望老师指点一下，还有，测试图像后是否有您的相关文章供我们引用呢。

**Comment by Linaom1214** [comment]
@liforeversong 可能是 streamlit 云上的资源不足，之前也有这种情况，没有写资源释放的代码 ，多检测几次就溢出了。这个只是一个简单的框架，模型都是经典的分割模型，你可以在上边替换自己的模型完成算法开发。我已经重启了应用，为了更好的体验建议在本地运行。现在已经恢复了

**Comment by liforeversong** [comment]
哇，太酷了，非常感谢Linaom1214老师！！！
