### ISSUE TITLE
请问大佬是否后期有支持swin-transformer的trt加速的计划？

### ISSUE THREAD

**Issue by tensorflowt** [Linaom1214/Infrared-detect-by-segmentation#2]

**Comment by Linaom1214** [comment]
这部分工作之前已经做完了， 没有做特殊优化，直接ONNX->TRT的技术路线，实现也比较简单，因为在弄毕设，之后会开源，

**Comment by Linaom1214** [comment]
> _No description provided._

这部分工作之前已经做完了， 没有做特殊优化，直接ONNX->TRT的技术路线，实现也比较简单，因为在弄毕设，之后会开源，

**Comment by tensorflowt** [comment]
大佬方便加一个微信吗？最近在做swin-transformer的tensorrt加速，有些环境版本问题需要和您确认一下？
微信：13474315223

**Comment by Linaom1214** [comment]
> 环境的话，TRT的官方docker 就可以，直接拉最新版的。
我记得是C++的环境也是OK的。

**Comment by tensorflowt** [comment]
> > 环境的话，TRT的官方docker 就可以，直接拉最新版的。
> > 我记得是C++的环境也是OK的。

大佬方便分享一下链接吗？
还有就是大佬的测试环境是基于什么硬件呢？

**Comment by Linaom1214** [comment]
> 
https://github.com/NVIDIA/TensorRT.git

测试环境
PC Ubuntu20.04 Cuda11.4 Tensort 8.2 1080Ti   
Jetson NX Jetpack 4.x

Jetson上目前较慢

**Comment by tensorflowt** [comment]
谢谢大佬，我这边使用了如下docker，直接使用也是可以的。
https://hub.docker.com/r/chaoyiyuan/tensorrt8
然后还有个疑问，就是我看您也有复现过开源的项目：
https://github.com/maggiez0138/Swin-Transformer-TensorRT
请问一下，你有遇到过这个问题吗？
![swin_trans_trt_001](https://user-images.githubusercontent.com/37217594/166680568-d30495e6-5a9d-4af3-8241-3b191d79f883.png)
我检查了一下，作者的trt目录下确实没有engine.py文件，您有遇到过这个问题吗？
（PS：其他测试脚本都没问题，唯独这个有问题。）
谢谢~

**Comment by Linaom1214** [comment]
> 

抱歉，可能我之前的标题有误导性，我的算法是融合了Swin Transformer的一部分，并不是之前使用Swin,  可以尝试自己先学习一下pytorch的onnx导出，再使用trt 的 导出 trt engine ，希望我这个仓库剋帮到您 https://github.com/Linaom1214/tensorrt-python.git 最后有帮助的话 感谢star

**Comment by tensorflowt** [comment]
> > 
> 
> 抱歉，可能我之前的标题有误导性，我的算法是融合了Swin Transformer的一部分，并不是之前使用Swin, 可以尝试自己先学习一下pytorch的onnx导出，再使用trt 的 导出 trt engine ，希望我这个仓库剋帮到您 https://github.com/Linaom1214/tensorrt-python.git 最后有帮助的话 感谢star

嗨！
非常感谢您的指导，然后我这边目前是已经可以实现upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1k.pth
模型的tensorRT加速了，具体的结果如下：
![eff8d9342fbe2235bece8d552e5fe8b](https://user-images.githubusercontent.com/37217594/167231948-068aa94a-bdef-4efc-852e-409828341744.png)
然后有个疑问，就是我这边使用的是mmseg的pytorch2onnx，然后他的工程目前是不支持动态batch的，这个您这边有没有好的建议呢？

非常感谢！

**Comment by Linaom1214** [comment]
> 

**动态Batch**，我这边没有相关的需求，突然好奇，动态batch的业务场景是什么样的呢？

可以加微信交流一下吗？ 18406583185
